CREATE TABLE IF NOT EXISTS properties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  city TEXT NOT NULL DEFAULT '',
  cover_image TEXT NOT NULL DEFAULT '/assets/liberty-hero.png',
  traveler_password_hash TEXT NOT NULL,
  openai_api_key TEXT NOT NULL DEFAULT '',
  openai_model TEXT NOT NULL DEFAULT 'gpt-5.5',
  ai_instructions TEXT NOT NULL DEFAULT '',
  welcome TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  gps TEXT NOT NULL DEFAULT '',
  wifi_ssid TEXT NOT NULL DEFAULT '',
  wifi_password TEXT NOT NULL DEFAULT '',
  ai_daily_limit INTEGER NOT NULL DEFAULT 80,
  ai_session_limit INTEGER NOT NULL DEFAULT 20,
  ai_max_input_chars INTEGER NOT NULL DEFAULT 700,
  public_description TEXT NOT NULL DEFAULT '',
  direct_booking_json TEXT NOT NULL DEFAULT '{}',
  data_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
